name: decider_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.6
  share_plus: ^9.0.0
  flutter_fortune_wheel: ^1.3.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/jpg/
